version: "3"

services:
    web:
        image: nginx:latest
        container_name: wpstarter_nginx
        ports:
            - "443:443"
        volumes:
            - ./wordpress:/var/www/html
            - ./.config/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./.config/nginx/server.conf:/etc/nginx/templates/server.template
            - ./.config/nginx/certs:/etc/nginx/certs
        depends_on:
            - php
        environment:
            - SSL_CERT_FILE=/etc/nginx/certs/localhost.crt
            - SSL_KEY_FILE=/etc/nginx/certs/localhost.key
    php:
        build:
            context: ./wordpress
        container_name: wpstarter_php
        restart: always
        volumes:
            - ./wordpress:/var/www/html
            - ./.config/php/fpm-pool.conf:/etc/php81/php-fpm.d/zzz.conf
            - ./.config/php/php.ini:/usr/local/etc/php/conf.d/local.ini
        env_file:
            - ./.config/env/wordpress-local.env
    mailhog:
        image: mailhog/mailhog:latest
        container_name: wpstarter_mailhog
        ports:
            - "1025:1025"
            - "8025:8025"
    mysql:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        container_name: wpstarter_db
        volumes:
            - ./.config/data/mysql:/var/lib/mysql
            - ./.config/data/logs/mysql:/var/log/mysql
            - ./.config/mysql:/etc/mysql/conf.d
            - ./.config/mysql/db.sql:/docker-entrypoint-initdb.d/db.sql
        environment:
            - MYSQL_DATABASE=wordpress
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_PASSWORD=password
            - MYSQL_ROOT_HOST=%
        cap_add:
            - SYS_NICE
        restart: always
        ports:
            - "3307:3306"
    redis:
        image: "redis:alpine"
        command: redis-server
        expose:
            - "6379"
        volumes:
            - redis-data:/data
            - redis-conf:/usr/local/etc/redis/redis.conf

volumes:
    redis-data:
    redis-conf:
        driver: local
